//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpTrackerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int expenseId { get; set; }
        public string expenseTitle { get; set; }
        public string expenseDesription { get; set; }
        public int categoryId { get; set; }
        public int expenseAmount { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual category category { get; set; }
    }
}
